
detector:
  device: 0
  weights: detection/ckpt/baseline/weights/best.pt
  threshold: 0.01

trackers:
  - 
    semantic : bus
    dup_iou: 0.6
    cls_id: 
      - 7
    bot_args:
      fuse: true
      match_thresh: 0.9
      track_high_thresh: 0.5
      track_low_thresh: 0.2
      new_track_thresh: 0.2
      with_reid: false
      track_buffer: 30
      proximity_thresh: 0.5

dataset:
  video_root: /datasets/roadpp/test_videos
  target_seq:
    - 100
